name: learn-github-actions
on: [push]
jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #     - run: npm install -g bats
  #     - run: bats -v
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # might not need node step
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: steveflint3/weather-app
          # ref: master
      - name: Start App
        run: |
          npm i
          npm start &
          echo "npm has started"
          sleep 20
          curl http://127.0.0.1:3000
          npx wait-on http://127.0.0.1:3000
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: steveflint3/weather-tests
          ref: main
      - name: Run NPM Test
        run: |
          npm i
          npm run cypress:run
    # - name: Upload Cypress Screenshots
      #   if: failure()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: cypress screenshots
      #     path: cypress/screenshots/