name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: steveflint3/weather-app
          # ref: master
      - name: Start App
        run: |
          npm i
          npm start &
          echo "npm has started"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: steveflint3/weather-tests
          ref: main
      - name: Run NPM Test
        run: npm run cypress:run
    # - name: Upload Cypress Screenshots
      #   if: failure()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: cypress screenshots
      #     path: cypress/screenshots/