name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run blog test
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://0.0.0.0:3000/'
          config: baseUrl=http://0.0.0.0:3000/