name: learn-github-actions
on: [push]
jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #     - run: npm install -g bats
  #     - run: bats -v
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: steveflint3/weather-app
          ref: master
      - name: Start App
        run: |
          npm install
          npm start & npx wait http://localhost:3000/
          echo "npm has started"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: steveflint3/weather-tests
          ref: main
      - name: Cypress run
        run: |
          lsof -Pi :3000 -sTCP:LISTEN
          npm i
          lsof -Pi :3000 -sTCP:LISTEN
          npm run cypress:run

    # - name: Upload Cypress Screenshots
      #   if: failure()
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: cypress screenshots
      #     path: cypress/screenshots/
